spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update